### ISSUE TITLE
Incorrect substring params in prefixFormatted

### ISSUE THREAD

**Issue by yrtimiD** [cesce/uuidv6-extension#1]
Looks like when you converted substr to substring [here](https://github.com/cesce/uuidv6-extension/blob/94351529ad0d0cc0182972342c36ea48b22e40f8/lib/index.ts#L118) you miscalculated parameters for the second chunk:
`${prefix.substr(8, 4)}` should be `${prefix.substr(8, 8+4)}`

**Comment by cesce** [comment]
Hi @yrtimiD, thanks in advance.

Let me test it and give you feedback.

**Comment by cesce** [comment]
Hi again @yrtimiD, thank you in advance.

Sorry the long delay.

Reviewed and merged.
